version: '2'
services:
  web-service:
    image: ....
    ...........
    expose: port
    
  web-nginx-basic-auth:
    image: nginx-basic-auth-proxy
    ports:
      - 0.0.0.0:8080:80
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - PROXY_PASS=http://web-service:port/
